### PR TITLE
[0001] Plugin Management

### PR DESCRIPTION
**Pull request by ojkelly**
> This is the initial proposal to manage plugins in Kombustion. It covers
retrieving plugins, standard locations and filenames for plugins, and a manifest
and lockfile to ensure consistency.

We'll update the RFC doc based on feedback, and the development of the feature.
This will be closed when either the feature is merged, or the RFC is voted down.

---

# Unresolved questions

- [x]  The output of `kombustion.lock` is auto-generated and not yet resolved.
- [x]  Global plugins, local plugins, or both?
- [x]  Multiple OS version of plugins.
    * Should one or multple be downloaded?
- [x]  The name of the `Plugin Directory`.
    * `~/.kombustion` for global plugins
    * `.kombustion` for local plugins
- [ ] `version-condition` see `kombustion.yaml`

### CODE REVIEW

**Comment by iann0036** [comment]
I don't mind the idea of Global vs. Local, but think they should both be called .kombustion (which will restrict locals in the users home dir...tough!).

I also think we should place BOTH the kombustion.yaml and kombustion.lock files within the .kombustion directory, as this keeps everything clean in a directory structure sense. The resultant structure may look like:

```
(root)
- README.md
-- .kombustion
--- kombustion.yaml
--- kombustion.lock
--- plugins
---- myplugin.so
- stackfiles (example only, named by the user)
-- mystack.yaml
```

**Comment by iann0036** [comment]
Also think kombustion add and kombustion install should be combined into the one operation. If you're in the very rare case where you don't want to add to the manifest but not download the plugin itself, either do it and remove the plugin binary or go modify it yourself.

**Comment by ojkelly** [comment]
@iann0036 re files, I think the manifest should stay top level of a project, but yeah the rest can go under `.kombustion`. The rationale being the manifest file could be human editable, whereas the rest are all taken care of by the tool.

`add` implicitly runs `install` after updating the manifest file. The main reason to expose `install` would be for CI. Given it's likely a simple addition to have `install` it seems less intuitive to omit it.

I think the stackfiles themselves can likely be left up to the user. I'd like to be able to have a stackfile next to lambda code for example (so not just a repo full of stackfiles).

**Comment by ojkelly** [comment]
Another idea I'd like for the manifest file. A `name` parameter, allowing you to name the project.

And then, if the `--stack-name` arg isn't provided we can then construct the stackname from `manifest.name--stackfilename--environment`.

This would remove the need to determine the stackname (which is sometimes more annoying than we think), and provides a sane default naming convention.

**Pull request closed without merging**
